name: CI

on:
  push:
    branches: [master, main, release]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci:
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          poetry run python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          poetry run python -m flake8 . --count --exit-zero --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          poetry run python -m pytest
